/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gbpe_policeass_utils_RgbInterpolation */

#ifndef _Included_gbpe_policeass_utils_RgbInterpolation
#define _Included_gbpe_policeass_utils_RgbInterpolation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gbpe_policeass_utils_RgbInterpolation
 * Method:    photoEnlarge
 * Signature: (Ljava/lang/String;IIILjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_gbpe_policeass_utils_RgbInterpolation_photoEnlarge
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
