/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gbpe_policeass_utils_VideoHandleUtils */

#ifndef _Included_gbpe_policeass_utils_VideoHandleUtils
#define _Included_gbpe_policeass_utils_VideoHandleUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gbpe_policeass_utils_VideoHandleUtils
 * Method:    ffmpegcore
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gbpe_policeass_utils_VideoHandleUtils_ffmpegcore
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
